print("I am going to make you a band name!")
print("First whats the name of your town?")
town = input()
print("Great, now whats the name of your first pet?")
pet = input()
print("Hmmmm.... Thinking... Ah yes. The name of your band should be")
print(town + pet)
